/** @format */

import {
  Buildings2,
  BagHappy,
  Briefcase,
  ShieldSecurity,
  Teacher,
  Building,
} from "iconsax-reactjs";

import NedayeMehrOmid from "../../assets/images/portfolio/nedayemehromid.webp";
import IranTobacco from "../../assets/images/portfolio/irantobaccoex.webp";
import BlackClothes from "../../assets/images/portfolio/blackclothes.webp";
import SahandBoresh from "../../assets/images/portfolio/sahandboresh.webp";
import JahanCharm from "../../assets/images/portfolio/jahancharm.webp";
import Ahangari from "../../assets/images/portfolio/ahangarimontazeri.webp";
import Kimia from "../../assets/images/portfolio/kimiapajoohan.webp";

export const portfolioItems = [
  {
    id: 1,
    title: "ندای مهر امید",
    slug: "nedayemehromid",
    domain: "nedayemehromid.ir",
    liveUrl: "https://nedayemehromid.ir",
    image: NedayeMehrOmid,
    gallery: [NedayeMehrOmid],
    icon: Buildings2,
    category: "شرکتی",
    client: "ندای مهر امید",
    role: "WordPress Developer",
    duration: "30 روز",
    year: "2025",
    status: "online",
    featured: true,
    overview:
      "طراحی و توسعه وب‌سایت شرکتی با تمرکز بر معرفی خدمات، سرعت، سئو و تجربه کاربری.",
    description:
      "وب‌سایت شرکتی با طراحی مدرن، ساختار اختصاصی و پنل مدیریت ساده برای معرفی خدمات و ارتباط با مشتریان.",
    challenge:
      "نیاز به وب‌سایتی سریع، حرفه‌ای و قابل توسعه برای معرفی خدمات مجموعه وجود داشت.",
    solution:
      "طراحی قالب اختصاصی وردپرس همراه با بهینه‌سازی سرعت، سئو و ساختار مدیریت محتوا.",
    features: [
      "طراحی ریسپانسیو",
      "بهینه‌سازی SEO",
      "سرعت بالا",
      "پنل مدیریت",
      "امنیت",
    ],
    technologies: ["WordPress", "PHP", "MySQL", "HTML5", "CSS3", "JavaScript"],
  },
  {
    id: 2,
    title: "ایران توتون",
    slug: "irantobaccoex",
    domain: "irantobaccoex.com",
    liveUrl: "https://irantobaccoex.com",
    image: IranTobacco,
    gallery: [IranTobacco],
    icon: Briefcase,
    category: "تجاری",
    client: "ایران توتون",
    role: "Full Stack WordPress Developer",
    duration: "40 روز",
    year: "2025",
    status: "online",
    featured: false,
    overview: "وب‌سایت معرفی محصولات و خدمات با ساختار اختصاصی.",
    description:
      "طراحی وب‌سایت شرکتی با تمرکز بر معرفی محصولات، خدمات و ایجاد پنل مدیریت قابل توسعه.",
    challenge:
      "نیاز به ساختار اختصاصی و مدیریت ساده اطلاعات محصولات وجود داشت.",
    solution: "پیاده‌سازی قالب اختصاصی و سیستم مدیریت محتوای بهینه.",
    features: ["پنل مدیریت", "ریسپانسیو", "SEO", "فرم ارتباط", "سرعت بالا"],
    technologies: ["WordPress", "PHP", "MySQL", "REST API"],
  },
  {
    id: 3,
    title: "بلک کلوز",
    slug: "blackclothes",
    domain: "blackclothes.ir",
    liveUrl: "https://blackclothes.ir",
    image: BlackClothes,
    gallery: [BlackClothes],
    icon: BagHappy,
    category: "فروشگاهی",
    client: "Black Clothes",
    role: "WooCommerce Developer",
    duration: "35 روز",
    year: "2024",
    status: "online",
    featured: false,
    overview: "فروشگاه اینترنتی پوشاک با تجربه خرید روان.",
    description:
      "طراحی فروشگاه اینترنتی با تمرکز بر رابط کاربری مدرن، سرعت بالا و فرآیند خرید آسان.",
    challenge: "نیاز به فروشگاهی سریع و کاربرپسند برای نمایش محصولات.",
    solution: "پیاده‌سازی WooCommerce همراه با طراحی اختصاصی.",
    features: [
      "سبد خرید",
      "درگاه پرداخت",
      "ریسپانسیو",
      "پنل مدیریت",
      "جستجوی محصولات",
    ],
    technologies: ["WooCommerce", "WordPress", "PHP", "CSS3"],
  },
  {
    id: 4,
    title: "سهند برش",
    slug: "sahandboresh",
    domain: "sahandboresh.com",
    liveUrl: "https://sahandboresh.com",
    image: SahandBoresh,
    gallery: [SahandBoresh],
    icon: Building,
    category: "صنعتی",
    client: "سهند برش",
    role: "WordPress Developer",
    duration: "28 روز",
    year: "2024",
    status: "online",
    featured: false,
    overview: "وب‌سایت معرفی خدمات صنعتی و محصولات.",
    description: "وب‌سایت شرکتی برای معرفی خدمات، تجهیزات و پروژه‌های صنعتی.",
    challenge: "نمایش صحیح خدمات صنعتی همراه با ساختار حرفه‌ای.",
    solution: "طراحی صفحات اختصاصی و بهینه‌سازی عملکرد سایت.",
    features: ["ریسپانسیو", "SEO", "پنل مدیریت", "فرم درخواست", "سرعت بالا"],
    technologies: ["WordPress", "PHP", "MySQL"],
  },
  {
    id: 5,
    title: "جهان چرم",
    slug: "jahan-charm",
    domain: "jahan-charm.ir",
    liveUrl: "https://jahan-charm.ir",
    image: JahanCharm,
    gallery: [JahanCharm],
    icon: BagHappy,
    category: "فروشگاهی",
    client: "جهان چرم",
    role: "WooCommerce Developer",
    duration: "32 روز",
    year: "2024",
    status: "online",
    featured: false,
    overview: "فروشگاه اینترنتی محصولات چرمی.",
    description:
      "طراحی فروشگاه اینترنتی با تمرکز بر نمایش حرفه‌ای محصولات و افزایش نرخ تبدیل.",
    challenge: "نمایش تعداد زیاد محصولات بدون افت سرعت.",
    solution: "بهینه‌سازی تصاویر و ساختار فروشگاه.",
    features: ["سبد خرید", "درگاه پرداخت", "ریسپانسیو", "SEO", "پنل مدیریت"],
    technologies: ["WooCommerce", "WordPress", "PHP"],
  },
  {
    id: 6,
    title: "آهنگری منتظری",
    slug: "ahangarimontazeri",
    domain: "ahangarimontazeri.ir",
    liveUrl: "https://ahangarimontazeri.ir",
    image: Ahangari,
    gallery: [Ahangari],
    icon: ShieldSecurity,
    category: "شرکتی",
    client: "آهنگری منتظری",
    role: "WordPress Developer",
    duration: "24 روز",
    year: "2024",
    status: "online",
    featured: false,
    overview: "وب‌سایت معرفی خدمات صنعتی.",
    description:
      "طراحی وب‌سایت اختصاصی برای معرفی خدمات و نمونه پروژه‌های صنعتی.",
    challenge: "نیاز به طراحی ساده اما حرفه‌ای برای جذب مشتریان صنعتی.",
    solution: "طراحی UI اختصاصی و مدیریت محتوای ساده.",
    features: ["ریسپانسیو", "امنیت", "SEO", "پنل مدیریت", "فرم تماس"],
    technologies: ["WordPress", "PHP", "MySQL"],
  },
  {
    id: 7,
    title: "کیمیا پژوهان",
    slug: "kimiapajoohan",
    domain: "kimiapajoohan.com",
    liveUrl: "https://kimiapajoohan.com",
    image: Kimia,
    gallery: [Kimia],
    icon: Teacher,
    category: "آزمایشگاهی",
    client: "کیمیا پژوهان",
    role: "WordPress Developer",
    duration: "26 روز",
    year: "2023",
    status: "online",
    featured: false,
    overview: "وب‌سایت معرفی خدمات آزمایشگاهی و پژوهشی.",
    description:
      "طراحی وب‌سایت مدرن جهت معرفی خدمات، تجهیزات و فعالیت‌های پژوهشی.",
    challenge: "دسته‌بندی مناسب اطلاعات علمی و خدمات آزمایشگاهی.",
    solution: "پیاده‌سازی ساختار محتوایی بهینه و طراحی مدرن.",
    features: ["SEO", "ریسپانسیو", "پنل مدیریت", "سرعت بالا", "امنیت"],
    technologies: ["WordPress", "PHP", "JavaScript"],
  },
];

export const portfolioCategories = [
  "همه",
  "شرکتی",
  "فروشگاهی",
  "تجاری",
  "صنعتی",
  "آزمایشگاهی",
  "فناوری",
  "خدمات",
  "خیریه",
];

export const portfolioSection = {
  badge: "نمونه‌کارها",
  title: "برخی از پروژه‌های اجرا شده",
  subtitle:
    "در سال‌های اخیر روی پروژه‌های شرکتی، فروشگاهی، صنعتی و اختصاصی متعددی فعالیت داشته‌ام. هر پروژه با تمرکز بر سرعت، امنیت، تجربه کاربری و توسعه‌پذیری پیاده‌سازی شده است.",
};
