/** @format */

/*
    User Permissions
*/

export const PERMISSIONS = Object.freeze({
  // Dashboard
  VIEW_DASHBOARD: "VIEW_DASHBOARD",

  // About
  CREATE_ABOUT: "CREATE_ABOUT",

  UPDATE_ABOUT: "UPDATE_ABOUT",

  DELETE_ABOUT: "DELETE_ABOUT",

  // Hero
  CREATE_HERO: "CREATE_HERO",

  UPDATE_HERO: "UPDATE_HERO",

  DELETE_HERO: "DELETE_HERO",

  // Portfolio
  CREATE_PORTFOLIO: "CREATE_PORTFOLIO",

  UPDATE_PORTFOLIO: "UPDATE_PORTFOLIO",

  DELETE_PORTFOLIO: "DELETE_PORTFOLIO",

  // Services
  CREATE_SERVICE: "CREATE_SERVICE",

  UPDATE_SERVICE: "UPDATE_SERVICE",

  DELETE_SERVICE: "DELETE_SERVICE",

  // Contact
  VIEW_CONTACTS: "VIEW_CONTACTS",

  DELETE_CONTACT: "DELETE_CONTACT",

  // Settings
  UPDATE_SETTINGS: "UPDATE_SETTINGS",

  // Upload
  UPLOAD_FILE: "UPLOAD_FILE",

  DELETE_FILE: "DELETE_FILE",
});
